name: publish to pypi
on:
  - push:
  - release:
    types: [published]
  - workflow_dispatch:
    inputs:
      test_deploy:
      description: 'test deploy to https://test.pypi.org'
      required: false
      default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependency
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -e .[tests]
      - name: Run Test
        run: |
          python -m pytest -ra
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
  deploy:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
  deploy_test:
    needs: build
    if: github.event.inputs.test_deploy == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check dists
        run: |
          echo "check dists"
          ls -al
      - name: Publish package to TestPyPI
        if: false
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/