name: unittest and publish to pypi
on:
  push:
    branches: [master]
  pull_request:
  release:
    types: [published]

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependency
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]
      - name: Run Test
        run: |
          python -m pytest -ra

  deploy:
    needs: unittest
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependency
        run: |
          python -m pip install --upgrade pip
          pip install wheel
      - name: Cache dist
        id: dist_cache
        uses: actions/cache@v2
        with:
          path: ./dist
          key: ${{ runner.os }}-dist-${{ github.sha }}
      - name: Build package
        id: build_package
        if: steps.dist_cache.outputs.cache-hit != 'true'
        run: |
          python setup.py sdist bdist_wheel
          echo "::notice:: $(ls -al dist)"
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
